### PR TITLE
VIH-8651 matching code to release 1.29 to check if this fixes pipeline.

### PR DESCRIPTION
**Pull request by khizarkhanu-hmcts**
### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/VIH-8651

### Change description ###

Updated references to match release 1.29

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

### CODE REVIEW

**Review by MichaelKeaneathmcts — DISMISSED** [review]

**Review by MichaelKeaneathmcts — APPROVED** [review]
It's nice to see that there is a fix for our problem here.

But it's not related to the pipeline issue.  As we discussed NO BRANCH will build - even those that have worked before.

**Review by FarronF — APPROVED** [review]

**Pull request merged**
